name: fchs_robotics
description: The FCHS Robotics App

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase: any

dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/members/

  fonts:
    - family: ConcertOne
      fonts:
        - asset: fonts/concertone-regular.ttf
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-ExtraLight.ttf
          weight: 100
        - asset: fonts/Nunito-Bold.ttf
          weight: 700